version: '3.9'

services:
  minecraftbedrock:
    container_name: minecraftbedrock
    image: itzg/minecraft-bedrock-server:latest
    environment:
      - UID=1026
      - GID=100
      - VERSION=LATEST
      - DIFFICULTY=normal # peaceful, easy, normal, hard
      - GAMEMODE=survival # survival, creative, adventure, spectator
      - SERVER_PORT=19132
      - SERVER_PORT_V6=19133
      - ONLINE_MODE=true
      - SERVER_NAME=steven.com
      - EULA=TRUE
      - PACKAGE_BACKUP_KEEP=true
      - LEVEL_TYPE=minecraft:normal # minecraft:normal, minecraft:flat, minecraft:large_biomes, minecraft:amplified, minecraft:single_biome_surface
      - ALLOW_CHEATS=false
      - MAX_PLAYERS=20
      - VIEW_DISTANCE=10
      - TICK_DISTANCE=4 # 4, 12
      - PLAYER_IDLE_TIMEOUT=30
      # - MAX_THREADS=8
    volumes:
      - mc-bedrock-data:/data
    ports:
      - 19132:19132/udp
      - 19133:19133/udp
    restart: unless-stopped