version: '3.9'

services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    environment:
      - EULA=true
    ports:
      - 25565:25565
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  data: